---
title: "Unit9BLT"
author: "Daniel Davieau"
date: "February 27, 2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy = TRUE)
```
## The RFacebook API
---  

First we need to get a temporary token
[Link to the Facebook ToolsExplorer](https://developers.facebook.com/tools/explorer/?method=GET&path=909402369070268&version=v2.12)  


>Now we load the RFacebook library and assign the token to a variable  


```{r}
library(Rfacebook)
token <- "EAACEdEose0cBALdEOVGuPJqvOhozRlb8AQ0LDOGn2QI2dHEPQcSPMxxqMSqGjLOoz2vgr3ZBX1JDnygTNqw3d6e3fAwvnfWAvp77uZB0JJWR92ocZA87ltWzBTkrRXUsbuRT4fpeuK6yLZCprpRzZABk7NdEubu9IP96HTwLPCJ7Irh1tZCgb7B3PBYEyqgQ4TqbcNWKFs6mFt0ZA67LVZBj4akrvHZCLSZC0b7FGFMRf2NwZDZD" 
```


> Try the getUsers function  


```{r}
me <- getUsers("909402369070268", token=token)
me
```


>Try the getFriends function with and without simplify  


```{r}
myfriends<- getFriends(token, simplify = FALSE)
#myfriends<- getFriends(token, simplify = TRUE)
myfriends
```
